title: kyryl horbushko
author:
  name: khorbushko
  email: kirill.ge@gmail.com
logo: /assets/favicon.png
description: >
  blog about diferent aspects of programming,
  mainly for iOS, using Swift/Obj-C

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  social_links:
    email: kirill.ge@gmail.com
    github: khorbushko
    stackoverflow: "2012219"
    linkedin: "kyryl-horbushko-67936bb5"

# Short bio or description (displayed in the header)
description: inspired by "software craftsmanship"

google_analytics: G-64DN886230
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - bookNotes.md
 - search.md
 - blog/archives/index.html
 - contact.md
 - about.md

theme: minima

donations:
  paypal:
    text:           PayPal Coffee
    id:             KKXW84CNZ5PGN
  mono:
    text:           Mono Coffee
  ua:
    text:           Support UA

comments:
  provider:            utterances
  
utterances:
  repo:                "khorbushko/khorbushko.github.io"
  label:               "Comments"
  theme:               "github-light"  

#discus
#disabled - use gitHUB issues instead
#disqus:
#  shortname: khorbushko-blog
#url: https://khorbushko.github.io

archive_path: blog/archives/

# Use the following plug-ins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll/web_monetization


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

paginate: 20
